services:
  restaurantapi:
    build:
      context: ./Dijo
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DijoConnectionString=Server=sqlserver,1433;Database=DijoDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"

  frontend:
    build:
      context: ../Frontend/e-gawulo
    ports:
      - "3000:5173"
    depends_on:
      - restaurantapi