// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantAPI.API.Data;

#nullable disable

namespace RestaurantAPI.Migrations
{
    [DbContext(typeof(DijoDbContext))]
    [Migration("20260514121149_UpdateImageFilePathTobeRelative")]
    partial class UpdateImageFilePathTobeRelative
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MenuRestaurants", b =>
                {
                    b.Property<Guid>("MenuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("restaurantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MenuId", "restaurantId");

                    b.HasIndex("restaurantId");

                    b.ToTable("MenuRestaurants", (string)null);
                });

            modelBuilder.Entity("RestaurantAPI.API.Models.Domain.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MenuIconImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("url_menu_icon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MenuIconImageId");

                    b.ToTable("Menu");

                    b.HasData(
                        new
                        {
                            Id = new Guid("83b89851-d594-48a0-b66b-94ba920a0c70"),
                            Description = "All your chicken menus",
                            Name = "Chicken",
                            created_at = new DateTime(2025, 2, 15, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            is_active = true
                        },
                        new
                        {
                            Id = new Guid("c5e708e3-46e5-49ff-bb27-a94cf56fa2fe"),
                            Description = "All your shisa nyama grills",
                            Name = "Grilled",
                            created_at = new DateTime(2025, 2, 27, 18, 15, 0, 0, DateTimeKind.Unspecified),
                            is_active = true
                        },
                        new
                        {
                            Id = new Guid("b7272c86-286d-465c-b993-10e177f6f056"),
                            Description = "All your Piza Menu",
                            Name = "Pizza",
                            created_at = new DateTime(2025, 3, 10, 20, 15, 0, 0, DateTimeKind.Unspecified),
                            is_active = true
                        },
                        new
                        {
                            Id = new Guid("769ad0e9-11b4-4c4d-955f-1efa80c04b9b"),
                            Description = "All your Burger Menu",
                            Name = "Burger",
                            created_at = new DateTime(2025, 4, 10, 20, 15, 0, 0, DateTimeKind.Unspecified),
                            is_active = true
                        },
                        new
                        {
                            Id = new Guid("ec4c5514-ae37-4b7c-ac36-671a3923f6ea"),
                            Description = "All healthy menus",
                            Name = "Healthy food",
                            created_at = new DateTime(2025, 2, 15, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            is_active = true
                        },
                        new
                        {
                            Id = new Guid("89b565b4-bf45-46e1-a798-17dd7df1fd94"),
                            Description = "All your Breakfast meals",
                            Name = "Breakfast",
                            created_at = new DateTime(2025, 2, 27, 18, 15, 0, 0, DateTimeKind.Unspecified),
                            is_active = true
                        },
                        new
                        {
                            Id = new Guid("58077521-cfc5-41a3-8414-5a5c8a7d4da3"),
                            Description = "All your Seafood Menu",
                            Name = "Seafood",
                            created_at = new DateTime(2025, 3, 10, 20, 15, 0, 0, DateTimeKind.Unspecified),
                            is_active = true
                        },
                        new
                        {
                            Id = new Guid("0c5074ec-73d6-40c1-810e-c5782d318feb"),
                            Description = "All your Indan Menu",
                            Name = "Indian Food",
                            created_at = new DateTime(2025, 4, 10, 20, 15, 0, 0, DateTimeKind.Unspecified),
                            is_active = true
                        });
                });

            modelBuilder.Entity("RestaurantAPI.API.Models.Domain.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RestaurantIconId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_open")
                        .HasColumnType("bit");

                    b.Property<string>("logo_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("93ec51ab-0862-47fe-a2be-b663c0d36971"),
                            Address = "101 Voortreker Kuilsriver",
                            created_at = new DateTime(2025, 4, 10, 20, 15, 0, 0, DateTimeKind.Unspecified),
                            description = "Chicken, Burgers, Chicken Wings, Fast Food, Light Meals, Portuguese, Salad, Spicy, Dessert, South African",
                            is_open = false,
                            logo_url = "nandos.jpg",
                            name = "Kuilsriver's Nandos",
                            rating = 3
                        },
                        new
                        {
                            Id = new Guid("9a9d2d84-e48f-4ff8-b2fa-c45b05421c82"),
                            Address = "102 Zevenwacht ",
                            created_at = new DateTime(2025, 4, 10, 20, 15, 0, 0, DateTimeKind.Unspecified),
                            description = "Burgers, Chicken, Portuguese, Salad, Wraps, Kids, Bowls",
                            is_open = false,
                            logo_url = "pedros.jpg",
                            name = "Pedros Zevenwacht",
                            rating = 3
                        },
                        new
                        {
                            Id = new Guid("0dc1443d-9e35-4940-810c-426f55e04ac7"),
                            Address = "04 Soneike ",
                            created_at = new DateTime(2025, 4, 10, 20, 15, 0, 0, DateTimeKind.Unspecified),
                            description = "Chicken, Chicken Wings, Burgers, Wraps, Fast Food, Dessert, American, Spicy, Light Meals, Milkshake",
                            is_open = false,
                            logo_url = "kfc.jpg",
                            name = "KFC Soneike",
                            rating = 3
                        },
                        new
                        {
                            Id = new Guid("1ad4de6c-f138-41d1-af4e-1d0d58e34b80"),
                            Address = "07 Vanreibeek Kuilsriver ",
                            created_at = new DateTime(2025, 4, 10, 20, 15, 0, 0, DateTimeKind.Unspecified),
                            description = "Chicken, Burgers, Chicken Wings, Fast Food, Spicy",
                            is_open = false,
                            logo_url = "hungryLion.jpg",
                            name = "Hungry Lion Kuils River",
                            rating = 3
                        },
                        new
                        {
                            Id = new Guid("caf21dbb-ade5-4f51-8f12-ef9862022ba9"),
                            Address = "07 Zevenwacht",
                            created_at = new DateTime(2025, 4, 10, 20, 15, 0, 0, DateTimeKind.Unspecified),
                            description = "Burgers, Chicken Wings, American, Fast Food, Plant-Based, Milkshake, Chicken",
                            is_open = false,
                            logo_url = "BurgerKing.jpg",
                            name = "Burger King Zevenwacht (Drive-thru)",
                            rating = 3
                        },
                        new
                        {
                            Id = new Guid("94053c61-d5f8-4d82-a0e8-c6fe2f1d5843"),
                            Address = "07 Haasendal",
                            created_at = new DateTime(2025, 4, 10, 20, 15, 0, 0, DateTimeKind.Unspecified),
                            description = "American, Breakfast, Burgers, Wraps, Cafe, Dessert, Fast Food, Milkshake, Plant-Based, Salad",
                            is_open = false,
                            logo_url = "McDonald .jpg",
                            name = "McDonald's Haasendal",
                            rating = 3
                        },
                        new
                        {
                            Id = new Guid("12b88f56-cc9a-4189-810e-6a1510f6045b"),
                            Address = "07 Stikland",
                            created_at = new DateTime(2025, 4, 10, 20, 15, 0, 0, DateTimeKind.Unspecified),
                            description = "Burgers, Chicken, Fries, Salad, Dessert, Kids, Plant-Based, Healthy, Ribs, Milkshake",
                            is_open = false,
                            logo_url = "Steers.jpg",
                            name = "Steers Total Stikland",
                            rating = 3
                        },
                        new
                        {
                            Id = new Guid("02d2951c-05a7-4768-b1bb-31891eb522ce"),
                            Address = "07 Soneike",
                            created_at = new DateTime(2025, 4, 10, 20, 15, 0, 0, DateTimeKind.Unspecified),
                            description = "Pizza, Pasta, Salad, Dessert, Mediterranean, Fruit, Fast Food, American, Non-Alcoholic",
                            is_open = false,
                            logo_url = "Romans.jpg",
                            name = "Roman's Pizza Soneike",
                            rating = 3
                        },
                        new
                        {
                            Id = new Guid("fbfd640e-03b5-4aef-95cf-6112708c4ce5"),
                            Address = "07 Kuilsriver",
                            created_at = new DateTime(2025, 4, 10, 20, 15, 0, 0, DateTimeKind.Unspecified),
                            description = "Pizza, Fast Food, Italian, Chicken Wings, Dessert, Vegetarian",
                            is_open = false,
                            logo_url = "debonairs.jpg",
                            name = "Debonairs Kuilsriver",
                            rating = 3
                        },
                        new
                        {
                            Id = new Guid("6d807253-5081-4928-8cea-ba0019f457a7"),
                            Address = "22 Kuilsriver Reno",
                            created_at = new DateTime(2025, 4, 10, 20, 15, 0, 0, DateTimeKind.Unspecified),
                            description = "Steakhouse, Grill, Burgers, Ribs, Chicken, Seafood, Chicken Wings, Dessert, Milkshake, Salad",
                            is_open = false,
                            logo_url = "spur.jpg",
                            name = "Spur Reno",
                            rating = 3
                        });
                });

            modelBuilder.Entity("RestaurantAPI.API.Models.Domain.SubMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_available")
                        .HasColumnType("bit");

                    b.Property<Guid>("restaurantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("restaurantId");

                    b.ToTable("SubMenu");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Domain.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("ImageType")
                        .HasColumnType("int");

                    b.Property<Guid?>("MenuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MenuItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RestaurantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("MenuItemId")
                        .IsUnique()
                        .HasFilter("[MenuItemId] IS NOT NULL");

                    b.HasIndex("RestaurantId")
                        .IsUnique()
                        .HasFilter("[RestaurantId] IS NOT NULL");

                    b.ToTable("Images", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("08fddb0b-c5f0-4350-93ff-08de5e5f95ae"),
                            FileExtension = ".gif",
                            FileName = "breakfast_menu.gif",
                            FilePath = "/Images/MenuIcon/breakfast_menu.gif",
                            FileSizeInBytes = 127884L,
                            ImageType = 1,
                            created_at = new DateTime(2026, 1, 28, 21, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("98e2bd9b-2f01-4e40-aead-0c06a9d266cb"),
                            FileExtension = ".gif",
                            FileName = "seafood_menu.gif",
                            FilePath = "/Images/MenuIcon/seafood_menu.gif",
                            FileSizeInBytes = 103380L,
                            ImageType = 1,
                            created_at = new DateTime(2026, 1, 28, 21, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b9c52ec7-517e-4de4-8a38-4151d9d674b0"),
                            FileExtension = ".gif",
                            FileName = "indian_menu.gif",
                            FilePath = "/Images/MenuIcon/indian_menu.gif",
                            FileSizeInBytes = 93504L,
                            ImageType = 1,
                            created_at = new DateTime(2026, 1, 28, 21, 20, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dfb0eb59-8ac5-431a-a0a2-b7a5a11ab130"),
                            FileExtension = ".gif",
                            FileName = "pizza_menu.gif",
                            FilePath = "/Images/MenuIcon/pizza_menu.gif",
                            FileSizeInBytes = 102576L,
                            ImageType = 1,
                            created_at = new DateTime(2026, 1, 28, 21, 25, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("81a98461-31bc-44d3-ac96-fb2947fb1ebe"),
                            FileExtension = ".gif",
                            FileName = "burger_menu.gif",
                            FilePath = "/Images/MenuIcon/burger_menu.gif",
                            FileSizeInBytes = 68224L,
                            ImageType = 1,
                            created_at = new DateTime(2026, 1, 28, 21, 20, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c374d2c3-4cf8-47c0-bc0b-4244296dc7ad"),
                            FileExtension = ".gif",
                            FileName = "chicken_menu.gif",
                            FilePath = "/Images/MenuIcon/chicken_menu.gif",
                            FileSizeInBytes = 127856L,
                            ImageType = 1,
                            created_at = new DateTime(2026, 1, 28, 21, 35, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2d089945-d41a-46d4-b165-f4635c078835"),
                            FileExtension = ".gif",
                            FileName = "grilled_menu.gif",
                            FilePath = "/Images/MenuIcon/grilled_menu.gif",
                            FileSizeInBytes = 83721L,
                            ImageType = 1,
                            created_at = new DateTime(2026, 1, 28, 21, 37, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b95753b9-8e2f-4d3e-a505-a3ac7aa47214"),
                            FileExtension = ".gif",
                            FileName = "healthy_menu.gif",
                            FilePath = "/Images/MenuIcon/healthy_menu.gif",
                            FileSizeInBytes = 360675L,
                            ImageType = 1,
                            created_at = new DateTime(2026, 1, 28, 21, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-1234-56789abcde01"),
                            FileExtension = ".jpeg",
                            FileName = "hungry_lion.jpeg",
                            FilePath = "/Images/RestaurantIcon/hungry_lion.jpeg",
                            FileSizeInBytes = 396632L,
                            ImageType = 2,
                            created_at = new DateTime(2026, 1, 9, 21, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b1c2d3e4-f5a6-7890-1234-56789abcde02"),
                            FileExtension = ".jpeg",
                            FileName = "kfc.jpeg",
                            FilePath = "/Images/RestaurantIcon/kfc.jpeg",
                            FileSizeInBytes = 377633L,
                            ImageType = 2,
                            created_at = new DateTime(2026, 1, 9, 21, 50, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c1d2e3f4-a5b6-7890-1234-56789abcde03"),
                            FileExtension = ".jpeg",
                            FileName = "nandos.jpeg",
                            FilePath = "/Images/RestaurantIcon/nandos.jpeg",
                            FileSizeInBytes = 361342L,
                            ImageType = 2,
                            created_at = new DateTime(2026, 1, 9, 21, 55, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d1e2f3a4-b5c6-7890-1234-56789abcde04"),
                            FileExtension = ".jpeg",
                            FileName = "pedros.jpeg",
                            FilePath = "/Images/RestaurantIcon/pedros.jpeg",
                            FileSizeInBytes = 373373L,
                            ImageType = 2,
                            created_at = new DateTime(2026, 1, 9, 22, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e1f2a3b4-c5d6-7890-1234-56789abcde05"),
                            FileExtension = ".jpeg",
                            FileName = "steers.jpeg",
                            FilePath = "/Images/RestaurantIcon/steers.jpeg",
                            FileSizeInBytes = 388298L,
                            ImageType = 2,
                            created_at = new DateTime(2026, 1, 9, 22, 5, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f1a2b3c4-d5e6-7890-1234-56789abcde06"),
                            FileExtension = ".jpeg",
                            FileName = "spur.jpeg",
                            FilePath = "/Images/RestaurantIcon/spur.jpeg",
                            FileSizeInBytes = 359922L,
                            ImageType = 2,
                            created_at = new DateTime(2026, 1, 9, 22, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a2b3c4d5-e6f7-7890-1234-56789abcde07"),
                            FileExtension = ".jpeg",
                            FileName = "debonairs.jpeg",
                            FilePath = "/Images/RestaurantIcon/debonairs.jpeg",
                            FileSizeInBytes = 382259L,
                            ImageType = 2,
                            created_at = new DateTime(2026, 1, 9, 22, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-7890-1234-56789abcde08"),
                            FileExtension = ".jpeg",
                            FileName = "romans.jpeg",
                            FilePath = "/Images/RestaurantIcon/romans.jpeg",
                            FileSizeInBytes = 392519L,
                            ImageType = 2,
                            created_at = new DateTime(2026, 1, 9, 22, 20, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c2d3e4f5-a6b7-7890-1234-56789abcde09"),
                            FileExtension = ".jpeg",
                            FileName = "macdonalds.jpeg",
                            FilePath = "/Images/RestaurantIcon/macdonalds.jpeg",
                            FileSizeInBytes = 267194L,
                            ImageType = 2,
                            created_at = new DateTime(2026, 1, 9, 22, 25, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d2e3f4a5-b6c7-7890-1234-56789abcde10"),
                            FileExtension = ".jpeg",
                            FileName = "burger_king.jpeg",
                            FilePath = "/Images/RestaurantIcon/burger_king.jpeg",
                            FileSizeInBytes = 371497L,
                            ImageType = 2,
                            created_at = new DateTime(2026, 1, 9, 22, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RestaurantAPI.Models.Domain.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MenuItemIconId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SubMenuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("imageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_Available")
                        .HasColumnType("bit");

                    b.Property<Guid>("restaurantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SubMenuId");

                    b.HasIndex("restaurantId");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("MenuRestaurants", b =>
                {
                    b.HasOne("RestaurantAPI.API.Models.Domain.Menu", null)
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantAPI.API.Models.Domain.Restaurant", null)
                        .WithMany()
                        .HasForeignKey("restaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantAPI.API.Models.Domain.Menu", b =>
                {
                    b.HasOne("RestaurantAPI.Models.Domain.Image", "MenuIconImage")
                        .WithMany()
                        .HasForeignKey("MenuIconImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MenuIconImage");
                });

            modelBuilder.Entity("RestaurantAPI.API.Models.Domain.SubMenu", b =>
                {
                    b.HasOne("RestaurantAPI.API.Models.Domain.Menu", "Menu")
                        .WithMany("SubMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantAPI.API.Models.Domain.Restaurant", "Restaurant")
                        .WithMany("SubMenus")
                        .HasForeignKey("restaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Domain.Image", b =>
                {
                    b.HasOne("RestaurantAPI.API.Models.Domain.Menu", "Menu")
                        .WithMany("Images")
                        .HasForeignKey("MenuId");

                    b.HasOne("RestaurantAPI.Models.Domain.MenuItem", "MenuItem")
                        .WithOne("MenuItemIcon")
                        .HasForeignKey("RestaurantAPI.Models.Domain.Image", "MenuItemId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RestaurantAPI.API.Models.Domain.Restaurant", "Restaurant")
                        .WithOne("RestaurantIcon")
                        .HasForeignKey("RestaurantAPI.Models.Domain.Image", "RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Menu");

                    b.Navigation("MenuItem");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Domain.MenuItem", b =>
                {
                    b.HasOne("RestaurantAPI.API.Models.Domain.SubMenu", "SubMenu")
                        .WithMany("MenuItems")
                        .HasForeignKey("SubMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantAPI.API.Models.Domain.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("restaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");

                    b.Navigation("SubMenu");
                });

            modelBuilder.Entity("RestaurantAPI.API.Models.Domain.Menu", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("SubMenus");
                });

            modelBuilder.Entity("RestaurantAPI.API.Models.Domain.Restaurant", b =>
                {
                    b.Navigation("RestaurantIcon");

                    b.Navigation("SubMenus");
                });

            modelBuilder.Entity("RestaurantAPI.API.Models.Domain.SubMenu", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Domain.MenuItem", b =>
                {
                    b.Navigation("MenuItemIcon");
                });
#pragma warning restore 612, 618
        }
    }
}
