// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantAPI.API.Data;

#nullable disable

namespace RestaurantAPI.Migrations
{
    [DbContext(typeof(DijoDbContext))]
    partial class DijoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantAPI.API.Models.Domain.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Menu");

                    b.HasData(
                        new
                        {
                            Id = new Guid("83b89851-d594-48a0-b66b-94ba920a0c70"),
                            Description = "All your chicken menus",
                            Name = "Chicken",
                            created_at = new DateTime(2025, 2, 15, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            is_active = true
                        },
                        new
                        {
                            Id = new Guid("c5e708e3-46e5-49ff-bb27-a94cf56fa2fe"),
                            Description = "All your shisa nyama grills",
                            Name = "Grilled",
                            created_at = new DateTime(2025, 2, 27, 18, 15, 0, 0, DateTimeKind.Unspecified),
                            is_active = true
                        },
                        new
                        {
                            Id = new Guid("b7272c86-286d-465c-b993-10e177f6f056"),
                            Description = "All your Piza Menu",
                            Name = "Piza",
                            created_at = new DateTime(2025, 3, 10, 20, 15, 0, 0, DateTimeKind.Unspecified),
                            is_active = true
                        });
                });

            modelBuilder.Entity("RestaurantAPI.API.Models.Domain.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_open")
                        .HasColumnType("bit");

                    b.Property<string>("logo_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("menuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("menuId");

                    b.ToTable("restaurants");
                });

            modelBuilder.Entity("RestaurantAPI.API.Models.Domain.SubMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SubMenuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_available")
                        .HasColumnType("bit");

                    b.Property<Guid>("restaurantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("SubMenuId");

                    b.HasIndex("restaurantId");

                    b.ToTable("SubMenu");
                });

            modelBuilder.Entity("RestaurantAPI.API.Models.Domain.Restaurant", b =>
                {
                    b.HasOne("RestaurantAPI.API.Models.Domain.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("menuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("RestaurantAPI.API.Models.Domain.SubMenu", b =>
                {
                    b.HasOne("RestaurantAPI.API.Models.Domain.Menu", "Menu")
                        .WithMany("SubMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantAPI.API.Models.Domain.SubMenu", null)
                        .WithMany("SubMenus")
                        .HasForeignKey("SubMenuId");

                    b.HasOne("RestaurantAPI.API.Models.Domain.Restaurant", "Restaurant")
                        .WithMany("SubMenus")
                        .HasForeignKey("restaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("RestaurantAPI.API.Models.Domain.Menu", b =>
                {
                    b.Navigation("SubMenus");
                });

            modelBuilder.Entity("RestaurantAPI.API.Models.Domain.Restaurant", b =>
                {
                    b.Navigation("SubMenus");
                });

            modelBuilder.Entity("RestaurantAPI.API.Models.Domain.SubMenu", b =>
                {
                    b.Navigation("SubMenus");
                });
#pragma warning restore 612, 618
        }
    }
}
