// <auto-generated />
using System;
using Dijo.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dijo.API.Migrations
{
    [DbContext(typeof(DijoDbContext))]
    [Migration("20250308085826_Seed Restaurant Data")]
    partial class SeedRestaurantData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dijo.API.Models.Domain.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<Guid>("restaurantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("restaurantId");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("Dijo.API.Models.Domain.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_available")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("MenuItem");
                });

            modelBuilder.Entity("Dijo.API.Models.Domain.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_open")
                        .HasColumnType("bit");

                    b.Property<string>("logo_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("restaurants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("83b89851-d594-48a0-b66b-94ba920a0c70"),
                            Address = "2282 Samjokozela Street",
                            created_at = new DateTime(2025, 2, 15, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            description = "It's finger lickin good",
                            is_open = true,
                            logo_url = "KFC.jpg",
                            name = "KFC",
                            rating = 3
                        },
                        new
                        {
                            Id = new Guid("c5e708e3-46e5-49ff-bb27-a94cf56fa2fe"),
                            Address = "40 Fairdale Street",
                            created_at = new DateTime(2025, 2, 27, 18, 15, 0, 0, DateTimeKind.Unspecified),
                            description = "WHere good food is",
                            is_open = false,
                            logo_url = "loza.jpg",
                            name = "Loza's braai vleis",
                            rating = 4
                        },
                        new
                        {
                            Id = new Guid("b7272c86-286d-465c-b993-10e177f6f056"),
                            Address = "11 Songwiqi Street",
                            created_at = new DateTime(2025, 3, 12, 14, 10, 0, 0, DateTimeKind.Unspecified),
                            description = "Where good time is found",
                            is_open = true,
                            logo_url = "ace.jpg",
                            name = "Kwa Ace",
                            rating = 5
                        });
                });

            modelBuilder.Entity("Dijo.API.Models.Domain.Menu", b =>
                {
                    b.HasOne("Dijo.API.Models.Domain.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("restaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Dijo.API.Models.Domain.MenuItem", b =>
                {
                    b.HasOne("Dijo.API.Models.Domain.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });
#pragma warning restore 612, 618
        }
    }
}
